[package]
name = "testserver"
version = "0.0.0"
description = "HTTP server for testing."
edition = "2018"
publish = false

[dependencies]
humantime = "2"
regex = "1.3"
threadpool = "1.8"
tiny_http = "0.7"
