[package]
name = "testserver"
version = "0.0.0"
description = "HTTP server for testing."
edition = "2018"
publish = false

[dependencies]
lazy_static = "1"
paste = "1"
regex = "1.3"
tiny_http = "0.7"
