name: commands
on:
  issue_comment:
    types: [created]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: rustfmt

      - id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          default: true

      - run: cargo fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply rustfmt
          branch: ${{ steps.comment-branch.outputs.head_ref }}
